#!/usr/bin/env python

import os
import sys
from os.path import exists

exe = "run_ekf"
source = " {0}".format( sys.argv[1] )
libs = " -I/Users/smithj1/ekf/lib"


if exists( exe ):
   os.remove( exe )

os.system( "c++ -std=c++11 -Wall -Wextra -stdlib=libc++ -o " + exe + source  + libs )
