#!/usr/bin/env python

import os
import sys
from os.path import exists

exe = " -o run_ekf"
source = " *.cpp "
#source = " {0}".format( sys.argv[1] )
libs = " -I/Users/smithj1/ekf/lib -I./"


if exists( exe ):
   os.remove( exe )

os.system( "c++ -std=c++11 -stdlib=libc++" + source  + libs + exe )
